#! /bin/bash

# Set up script used in both the Dockerfile and the Makefile, while building and installing Attendize in any environment.
composer install --no-interaction
cp .env.example .env
chmod -R a+w .env
chmod -R a+w storage/
chmod -R a+w bootstrap/cache/
php artisan key:generate
php artisan migrate
